### ISSUE TITLE
Trigger Service Hanging

### ISSUE THREAD

**Issue by marlow-fawn** [pinorobotics/jros2services#1]
Hello, unsure if this is an issue with just a malformed service definition. I'm attempting to call the Trigger service with the following:

https://docs.ros.org/en/noetic/api/std_srvs/html/srv/Trigger.html

I've attached my service definition. I don't seem to be getting any error messages, and it seems to find the standReply topic and subscribe to it. Is it an issue of an empty request? Or a response issue?

I'm using Humble, with client 9.0 and services 6.0

[Trigger.zip](https://github.com/user-attachments/files/16147340/Trigger.zip)

**Comment by marlow-fawn** [comment]
Any updates on this?

**Comment by lambdaprime** [comment]
Hi @marlow-fawn,

Thanks for using **jrosclient**

We are looking into it and will update you next week

Regards,

**Comment by lambdaprime** [comment]
Hi @marlow-fawn ,

The fix is ready and will be included in the next version of **jros2services** we plan to release.

Until then please add dependency on [jros2message v9](https://github.com/lambdaprime/jros2messages/blob/main/jros2messages/release/CHANGELOG.md) where this issue is fixed.

Regards,

**Comment by lambdaprime** [comment]
Hi @marlow-fawn 

This issue is fixed in [version 7](https://github.com/pinorobotics/jros2services/blob/main/jros2services/release/CHANGELOG.md) we recently released

Regards,
